import { Download, FileCode2, LoaderCircle, PackagePlus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { BootstrapPayload, DoctorSnapshot } from '../../../src/application/types';
import { installSkill, uninstallSkill } from '../api';
import { PageHeading, shortPath } from '../components/ui';

export function ManagePage({ bootstrap, snapshot, onChanged, setToast }: { bootstrap: BootstrapPayload | null; snapshot: DoctorSnapshot | null; onChanged: () => void; setToast: (message: string) => void }) {
  const [sourceType, setSourceType] = useState<'local' | 'marketplace'>('local'); const [source, setSource] = useState(''); const [target, setTarget] = useState('claude'); const [link, setLink] = useState(false); const [busy, setBusy] = useState(false); const [localError, setLocalError] = useState<string | null>(null);
  const submit = async () => { setBusy(true); setLocalError(null); try { const result = await installSkill({ source, sourceType, target, link }); setToast(`已安装 ${result.name}`); setSource(''); onChanged(); } catch (error) { setLocalError(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); } };
  return <section><PageHeading title="管理与导出" subtitle="安装受信任的 skill、管理已登记资源并导出报告。"><a className="button secondary" href="/api/export/dashboard" download><Download size={16} />导出报告</a></PageHeading>
    <div className="manage-grid"><section className="panel install-panel"><div className="panel-heading"><div><h3>安装 Skill</h3><p>支持本地路径或 skills.sh slug</p></div><PackagePlus size={20} /></div>
      <div className="segmented"><button className={sourceType === 'local' ? 'active' : ''} onClick={() => setSourceType('local')}>本地文件</button><button className={sourceType === 'marketplace' ? 'active' : ''} onClick={() => setSourceType('marketplace')}>Marketplace</button></div>
      <label className="field"><span>{sourceType === 'local' ? 'SKILL.md 或目录路径' : 'Skill slug'}</span><input value={source} onChange={(event) => setSource(event.target.value)} placeholder={sourceType === 'local' ? '/path/to/my-skill' : 'owner/skill-name'} /></label>
      <label className="field"><span>安装到</span><select value={target} onChange={(event) => setTarget(event.target.value)}>{bootstrap?.supportedPlatforms.filter((value) => value !== 'unknown').map((value) => <option key={value}>{value}</option>)}</select></label>
      {sourceType === 'local' && <label className="check-row"><input type="checkbox" checked={link} onChange={(event) => setLink(event.target.checked)} />使用符号链接，便于同步本地修改</label>}{localError && <p className="form-error">{localError}</p>}
      <button className="button primary full" disabled={!source.trim() || busy} onClick={() => void submit()}>{busy ? <LoaderCircle className="spin" size={17} /> : <PackagePlus size={17} />}安装</button>
    </section><section className="panel"><div className="panel-heading"><div><h3>扫描与报告</h3><p>保留本地诊断结果用于分享</p></div><FileCode2 size={20} /></div><div className="action-list"><div><span>静态 HTML 报告</span><small>包含资源、冲突、安全和清理建议</small></div><a className="button secondary" href="/api/export/dashboard" download>下载</a><div><span>当前快照</span><small>{snapshot ? `${snapshot.summary.resources} 个资源 · ${snapshot.summary.issues} 个问题` : '尚未扫描'}</small></div><span className="muted">{snapshot ? new Date(snapshot.generatedAt).toLocaleString() : '—'}</span></div></section></div>
    <section className="panel registry-panel"><div className="panel-heading"><div><h3>已登记安装</h3><p>通过 Skill Doctor 安装的全局 skills</p></div><span className="result-count">{bootstrap?.registry.length ?? 0}</span></div><div className="registry-list">{bootstrap?.registry.map((entry) => <div className="registry-row" key={`${entry.platform}:${entry.name}`}><div><code>{entry.name}</code><small>{entry.platform} · {entry.source} · {shortPath(entry.installedPath)}</small></div><button className="button danger compact" onClick={async () => { if (!window.confirm(`确认卸载 ${entry.name}？`)) return; try { await uninstallSkill({ name: entry.name, platform: entry.platform, force: false }); setToast(`已卸载 ${entry.name}`); onChanged(); } catch (error) { if (window.confirm(`${error instanceof Error ? error.message : error}\n是否强制卸载？`)) { await uninstallSkill({ name: entry.name, platform: entry.platform, force: true }); setToast(`已强制卸载 ${entry.name}`); onChanged(); } } }}><Trash2 size={15} />卸载</button></div>)}{!bootstrap?.registry.length && <p className="muted empty-copy">还没有通过 Skill Doctor 安装的资源。</p>}</div></section>
  </section>;
}
